
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASTERISK COMMA DELETE EQUALS FROM ID INSERT INTO LPAREN NUMBER RPAREN SELECT SET UPDATE VALUES WHEREstatement : SELECT column_list FROM ID\n                 | SELECT column_list FROM ID WHERE ID EQUALS NUMBERcolumn_list : ASTERISK\n                   | ID\n                   | ID COMMA column_liststatement : INSERT INTO ID LPAREN column_list RPAREN VALUES LPAREN value_list RPARENvalue_list : NUMBER\n                  | NUMBER COMMA value_liststatement : UPDATE ID SET ID EQUALS NUMBER WHERE ID EQUALS NUMBERstatement : DELETE FROM ID WHERE ID EQUALS NUMBER'
    
_lr_action_items = {'SELECT':([0,],[2,]),'INSERT':([0,],[3,]),'UPDATE':([0,],[4,]),'DELETE':([0,],[5,]),'$end':([1,17,33,34,40,42,],[0,-1,-10,-2,-6,-9,]),'ASTERISK':([2,13,19,],[8,8,8,]),'ID':([2,4,9,11,12,13,15,19,21,22,32,],[7,10,14,16,17,7,20,7,25,26,36,]),'INTO':([3,],[9,]),'FROM':([5,6,7,8,18,],[11,12,-4,-3,-5,]),'RPAREN':([7,8,18,23,37,38,43,],[-4,-3,-5,27,40,-7,-8,]),'COMMA':([7,38,],[13,41,]),'SET':([10,],[15,]),'LPAREN':([14,31,],[19,35,]),'WHERE':([16,17,28,],[21,22,32,]),'EQUALS':([20,25,26,36,],[24,29,30,39,]),'NUMBER':([24,29,30,35,39,41,],[28,33,34,38,42,38,]),'VALUES':([27,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'column_list':([2,13,19,],[6,18,23,]),'value_list':([35,41,],[37,43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> SELECT column_list FROM ID','statement',4,'p_statement_select','analizador.py',77),
  ('statement -> SELECT column_list FROM ID WHERE ID EQUALS NUMBER','statement',8,'p_statement_select','analizador.py',78),
  ('column_list -> ASTERISK','column_list',1,'p_column_list','analizador.py',82),
  ('column_list -> ID','column_list',1,'p_column_list','analizador.py',83),
  ('column_list -> ID COMMA column_list','column_list',3,'p_column_list','analizador.py',84),
  ('statement -> INSERT INTO ID LPAREN column_list RPAREN VALUES LPAREN value_list RPAREN','statement',10,'p_statement_insert','analizador.py',88),
  ('value_list -> NUMBER','value_list',1,'p_value_list','analizador.py',92),
  ('value_list -> NUMBER COMMA value_list','value_list',3,'p_value_list','analizador.py',93),
  ('statement -> UPDATE ID SET ID EQUALS NUMBER WHERE ID EQUALS NUMBER','statement',10,'p_statement_update','analizador.py',97),
  ('statement -> DELETE FROM ID WHERE ID EQUALS NUMBER','statement',7,'p_statement_delete','analizador.py',101),
]
